# Generated by Django 5.2.8 on 2025-11-12 23:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('employee_id', models.CharField(max_length=6, primary_key=True, serialize=False, unique=True, verbose_name='ID de Empleado')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=100, verbose_name='Apellido')),
                ('dni', models.CharField(max_length=8, unique=True, verbose_name='DNI')),
                ('cuil', models.CharField(max_length=11, unique=True, verbose_name='CUIL')),
                ('foto_perfil', models.ImageField(blank=True, null=True, upload_to='empleados/', verbose_name='Foto de Perfil')),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1, verbose_name='Género')),
                ('edad', models.IntegerField(verbose_name='Edad')),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('estado_civil', models.CharField(choices=[('soltero', 'Soltero/a'), ('casado', 'Casado/a'), ('divorciado', 'Divorciado/a'), ('viudo', 'Viudo/a')], max_length=20, verbose_name='Estado Civil')),
                ('tiene_hijos', models.BooleanField(default=False, verbose_name='Tiene Hijos')),
                ('nombre_domicilio', models.CharField(max_length=200, verbose_name='Nombre del Domicilio')),
                ('numero_departamento', models.CharField(blank=True, max_length=10, null=True, verbose_name='Número de Departamento')),
                ('piso_departamento', models.CharField(blank=True, max_length=10, null=True, verbose_name='Piso de Departamento')),
                ('numero_casa', models.CharField(blank=True, max_length=10, null=True, verbose_name='Número de Casa')),
                ('numero_emergencia', models.CharField(max_length=20, verbose_name='Número de Emergencia')),
                ('position', models.CharField(default='Empleado', max_length=100, verbose_name='Cargo')),
                ('is_manager', models.BooleanField(default=False, verbose_name='Es Gerente')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('password', models.CharField(max_length=128, verbose_name='Contraseña')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
            },
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateTimeField(auto_now_add=True, verbose_name='Hora de Entrada')),
                ('check_out', models.DateTimeField(blank=True, null=True, verbose_name='Hora de Salida')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Fecha')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_asistencia', to=settings.AUTH_USER_MODEL, verbose_name='Empleado')),
            ],
            options={
                'verbose_name': 'Registro de Asistencia',
                'verbose_name_plural': 'Registros de Asistencia',
                'ordering': ['-check_in'],
            },
        ),
    ]
