# Generated by Django 5.2.7 on 2025-11-17 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='numero_telefono',
            field=models.CharField(default='', max_length=20, verbose_name='Número de Telefono'),
            preserve_default=False,
        ),
    ]
