# Generated by Django 5.2.8 on 2025-11-17 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_asistencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='codigo_biometrico',
            field=models.IntegerField(blank=True, null=True, verbose_name='Código Biométrico'),
        ),
    ]
