# Generated by Django 5.2.8 on 2025-11-17 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_employee_codigo_biometrico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='codigo_biometrico',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='Código biométrico'),
        ),
    ]
