# Generated by Django 5.2.8 on 2025-11-18 18:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_employee_codigo_biometrico'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistencia',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
